apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudquery
  labels:
    app: cloudquery
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cloudquery
              image: ghcr.io/cloudquery/cloudquery:latest
              imagePullPolicy: IfNotPresent
              args: ["sync", "/config/config.yml", "--log-console", "--log-format", "json"]
              env:
                - name: AWS_ACCOUNT_NAME
                  valueFrom:
                    secretKeyRef:
                      name: cloudquery-secret-<aws-account>
                      key: AWS_ACCOUNT_NAME
                - name: AWS_ROLE_ARN
                  valueFrom:
                    secretKeyRef:
                      name: cloudquery-secret-<aws-account>
                      key: AWS_ROLE_ARN
              envFrom:
                - secretRef:
                    name: cloudquery-secret
              volumeMounts:
              - name: config
                mountPath: "/config"
                readOnly: true
          restartPolicy: Never
          volumes:
          - name: config
            configMap:
              name: cloudquery-config
              items:
              - key: "config"
                path: "config.yml"
